name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Create application.properties
      run: |
        cat > src/main/resources/application.properties << EOL
        spring.application.name=account-service
        spring.datasource.url=${{ secrets.DB_URL }}
        spring.datasource.username=${{ secrets.DB_USERNAME }}
        spring.datasource.password=${{ secrets.DB_PASSWORD }}
        spring.jpa.hibernate.ddl-auto=update
        spring.jpa.show-sql=true
        spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
        server.port=8081
        EOL
        
    - name: Run Tests
      run: mvn test
      
    - name: Build Docker Image
      if: github.ref == 'refs/heads/main'
      run: |
        docker build -t account-service:${{ github.sha }} .
        
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker Image
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag account-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/account-service:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/account-service:latest 